name: Yandex.Cloud CI
on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: whynothugo/python-linting@master
  testing:
    needs: [linting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Discovering test
        run: python3 -m unittest discover -v tests/
  deploy:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@master
        with:
          token: ${{ secrets.YC_TOKEN }}
          function_id: ${{ secrets.YC_FUNCTION_ID }}
          runtime: 'python37-preview'
          entrypoint: 'main.handler'
          environment: DEBUG=True,USER_ACCESS_ID=${{ secrets.SERVICE_USER_ACCESS_ID }},USER_ACCESS_SECRET=${{ secrets.SERVICE_USER_ACCESS_SECRET }},BUCKET=${{ secrets.YC_BUCKET }}
          source: '.'