name: Yandex.Cloud CI
on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
      - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
      - name: Installing flake8
        run: python3 -m pip install flake8
      - name: Linting main.py
        run: python3 -m flake8 main.py
      - name: Linting all tests cases
        run: python3 -m flake8 tests/*
  testing:
    needs: [linting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
      - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
      - name: Installing dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Discovering test
        run: python3 -m unittest discover -v tests/
  deploy:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@master
        with:
          token: ${{ secrets.YC_TOKEN }}
          function_id: ${{ secrets.YC_FUNCTION_ID }}
          runtime: 'python37-preview'
          entrypoint: 'main.handler'
          environment: DEBUG=True,USER_ACCESS_ID=${{ secrets.SERVICE_USER_ACCESS_ID }},USER_ACCESS_SECRET=${{ secrets.SERVICE_USER_ACCESS_SECRET }},BUCKET=${{ secrets.YC_BUCKET }}
          source: '.'